### ISSUE TITLE
pod  requirements error

### ISSUE THREAD

**Issue by notedit** [Kickflip/kickflip-ios-example#3]
[!] Unable to satisfy the following requirements:
- `Kickflip (from`Submodules/kickflip-ios-sdk/Kickflip.podspec`)` required by `Podfile`

**Comment by Allan-Nava** [comment]
Hi, I got this error:

![screen shot 2017-10-20 at 15 15 42](https://user-images.githubusercontent.com/22498435/31822585-979b4bd4-b5a9-11e7-9af6-d31546d67fe0.png)
